![New York City schoolbus](schoolbus.jpg)

Foto de [Jannis Lucas](https://unsplash.com/@jannis_lucas) no [Unsplash](https://unsplash.com).
<br>

Todos os anos, estudantes do ensino médio nos Estados Unidos fazem o SAT, um exame padronizado que mede habilidades de leitura, matemática e escrita. São três seções — leitura, matemática e escrita — cada uma com **pontuação máxima de 800 pontos**. Essas provas são extremamente importantes para estudantes e universidades, pois têm um papel central no processo de admissão.

Analisar o desempenho das escolas é importante para diversos públicos, incluindo profissionais de políticas e educação, pesquisadores, governo e até pais que estão escolhendo em qual escola matricular seus filhos.

Você recebeu um conjunto de dados chamado `schools.csv`, com uma prévia abaixo.

Sua tarefa é responder a três perguntas essenciais sobre o desempenho no SAT das escolas públicas de Nova York (NYC).

In [114]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [115]:
schools.describe()

       average_math  average_reading  average_writing  percent_tested
count    375.000000       375.000000       375.000000      355.000000
mean     432.944000       424.504000       418.458667       64.976338
std       71.952373        61.881069        64.548599       18.747634
min      317.000000       302.000000       284.000000       18.500000
25%      386.000000       386.000000       382.000000       50.950000
50%      415.000000       413.000000       403.000000       64.800000
75%      458.500000       445.000000       437.500000       79.600000
max      754.000000       697.000000       693.000000      100.000000

In [116]:
filter_best_math_schools = schools[schools['average_math'] >= (0.8 * 800)]
best_math_schools = math_best_df[['school_name', 'average_math']].sort_values(by = 'average_math', ascending = False)

best_math_schools

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

In [117]:
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']

top_10_schools = top_10_schools = schools[['school_name', 'total_SAT']].sort_values(by = 'total_SAT', ascending = False)[:10]

top_10_schools

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

In [118]:
num_schools = schools.groupby('borough')['school_name'].count()
average_SAT = schools.groupby('borough')['total_SAT'].mean()
std_SAT = schools.groupby('borough')['total_SAT'].std()

borough_stats = pd.DataFrame({
    'num_schools': num_schools,
    'average_SAT': average_SAT,
    'std_SAT': std_SAT
})

largest_std_dev = borough_stats[borough_stats['std_SAT'] == std_SAT.max()].reset_index().round(2)

largest_std_dev

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29